Repository Jenyus-Org/recog, pull requests merged in 2021-04, with the labels that each got.

#12 [ENHANCEMENT] Sign-Up Process
  pages/signup.tsx
Labels: enhancement

#16 [ENHANCEMENT] Authenticatation in Apollo Client / Submit Post
  .eslintrc.js
  pages/forum/submit.tsx
  pages/login.tsx
  src/components/Sidenav.tsx
  src/context/auth.tsx
  src/lib/apolloClient.ts
Labels: enhancement

#17 [ENHANCEMENT] Next-Auth.js for Authentication
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/forum/submit.tsx
  pages/login.tsx
  pages/signup.tsx
  src/components/Sidenav.tsx
  src/context/auth.tsx
  src/context/user.tsx
  src/hookes/useAuthenticatedUser.ts
  src/hookes/useJwt.ts
  src/lib/apolloClient.ts
  yarn.lock
Labels: enhancement

#18 [ENHANCEMENT] Refresh Access Token
  pages/api/auth/[...nextauth].ts
  src/lib/apolloClient.ts
  src/lib/refreshAccessToken.ts
Labels: bug, enhancement

#21 [ENHANCEMENT] Fix Login Route Callback URL and Add to Redirects
  pages/forum/submit.tsx
  pages/login.tsx
  src/components/Sidenav.tsx
Labels: enhancement

#22 [ENHANCEMENT] Remove User from Token if Refresh Access Token Fails
  pages/forum/submit.tsx
  pages/login.tsx
  src/components/Sidenav.tsx
  src/lib/refreshAccessToken.ts
Labels: bug

#23 [ENHANCEMENT] Add Lint Plugins & Rules
  .eslintrc.js
  .github/workflows/lint-recog.yml
  pages/signup.tsx
  src/components/Post.tsx
Labels: enhancement

#25 [ENHANCEMENT/BUG] Sign-Up Page Callback URL / Yup Form Typing
  pages/forum/submit.tsx
  pages/login.tsx
  pages/signup.tsx
Labels: bug, enhancement
